### 데이터 정제 및 준비

In [10]:
import numpy as np
import pandas as pd

In [11]:
float_data = pd.Series([1.2,-3.5,np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [12]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [13]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [14]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [15]:
float_data = pd.Series([1,2,None], dtype = 'float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [16]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [17]:
data = pd.Series([1,np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [18]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [19]:
data = pd.DataFrame([[1.,6.5, 3.], [1.,np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [21]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [22]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [23]:
data.dropna(axis = "columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4,1] =np.nan
df.iloc[:2,2] = np.nan
df

0         1         2
0 -0.117941       NaN       NaN
1 -1.158893       NaN       NaN
2  0.346600       NaN -0.351288
3 -0.199435       NaN -0.784690
4  1.442495 -1.903461 -0.432551
5 -0.907062  0.135121  0.212580
6 -0.475528  1.629981 -0.406021

In [25]:
df.dropna()

0         1         2
4  1.442495 -1.903461 -0.432551
5 -0.907062  0.135121  0.212580
6 -0.475528  1.629981 -0.406021

In [26]:
df.dropna(thresh = 2)

0         1         2
2  0.346600       NaN -0.351288
3 -0.199435       NaN -0.784690
4  1.442495 -1.903461 -0.432551
5 -0.907062  0.135121  0.212580
6 -0.475528  1.629981 -0.406021

In [27]:
df.fillna(0)

0         1         2
0 -0.117941  0.000000  0.000000
1 -1.158893  0.000000  0.000000
2  0.346600  0.000000 -0.351288
3 -0.199435  0.000000 -0.784690
4  1.442495 -1.903461 -0.432551
5 -0.907062  0.135121  0.212580
6 -0.475528  1.629981 -0.406021

In [28]:
df.fillna({1:0.5, 2:0})

0         1         2
0 -0.117941  0.500000  0.000000
1 -1.158893  0.500000  0.000000
2  0.346600  0.500000 -0.351288
3 -0.199435  0.500000 -0.784690
4  1.442495 -1.903461 -0.432551
5 -0.907062  0.135121  0.212580
6 -0.475528  1.629981 -0.406021

In [29]:
df = pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:,1] = np.nan
df.iloc[4:,2] = np.nan
df

0         1         2
0 -0.055671  0.136926  0.271604
1 -2.245939  1.611933  2.311805
2 -1.138124       NaN  0.410944
3  0.431267       NaN  0.834550
4  0.114070       NaN       NaN
5 -0.329244       NaN       NaN

In [30]:
df.fillna(method = "ffill")

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\1983593268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill")


0         1         2
0 -0.055671  0.136926  0.271604
1 -2.245939  1.611933  2.311805
2 -1.138124  1.611933  0.410944
3  0.431267  1.611933  0.834550
4  0.114070  1.611933  0.834550
5 -0.329244  1.611933  0.834550

In [31]:
df.fillna(method = "ffill", limit = 2)

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\1904396064.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill", limit = 2)


0         1         2
0 -0.055671  0.136926  0.271604
1 -2.245939  1.611933  2.311805
2 -1.138124  1.611933  0.410944
3  0.431267  1.611933  0.834550
4  0.114070       NaN  0.834550
5 -0.329244       NaN  0.834550

In [85]:
data = pd.Series([1.,np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [87]:
data = pd.Series({"k1": ["one", "two"] * 3 + ["two"], "k2": [1,1,2,3,3,4,4]})
data

k1    [one, two, one, two, one, two, two]
k2                  [1, 1, 2, 3, 3, 4, 4]
dtype: object

In [101]:
data.duplicated()

k1    False
k2    False
v1    False
dtype: bool

In [103]:
data.drop_duplicates()

k1    [one, two, one, two, one, two, two]
k2                  [1, 1, 2, 3, 3, 4, 4]
v1                  (0, 1, 2, 3, 4, 5, 6)
dtype: object

In [105]:
data["v1"] = range(7)
data

k1    [one, two, one, two, one, two, two]
k2                  [1, 1, 2, 3, 3, 4, 4]
v1                  (0, 1, 2, 3, 4, 5, 6)
dtype: object

In [107]:
data.drop_duplicates(subset=["k1"])

TypeError: Series.drop_duplicates() got an unexpected keyword argument 'subset'

In [109]:
data.drop_duplicates(["k1","k2"], keep="last")

TypeError: Series.drop_duplicates() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

In [111]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon", "pastrami","corned beef", "bacon","pastrami", "honey ham","nova lox"],
                     "ounces": [4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [121]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [123]:
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [125]:
def get_animal(x):
    return meat_to_animal[x]

data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [127]:
data = pd.Series([1., -999.,2.,-999., -1000, 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [129]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [131]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [133]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [135]:
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [137]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index = ["Ohio", "Colorado", "New York"],
                    columns = ["one", "two", "three", "four"])

In [139]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [141]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [143]:
data.rename(index=str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [145]:
data.rename(index = {"Ohio":"INDIANA"},
            columns = {"three": "peekaboo"})

one  two  peekaboo  four
OHIO    0    1         2     3
COLO    4    5         6     7
NEW     8    9        10    11

#### 이산화

In [152]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
age_categories = pd.cut(ages, bins) 
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [154]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [156]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [158]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [160]:
pd.value_counts(age_categories)

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [162]:
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [164]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages,bins,labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [166]:
data = np.random.uniform(size = 20)
pd.cut(data,4,precision = 2)

[(0.29, 0.51], (0.74, 0.97], (0.74, 0.97], (0.057, 0.29], (0.74, 0.97], ..., (0.51, 0.74], (0.51, 0.74], (0.057, 0.29], (0.51, 0.74], (0.29, 0.51]]
Length: 20
Categories (4, interval[float64, right]): [(0.057, 0.29] < (0.29, 0.51] < (0.51, 0.74] < (0.74, 0.97]]

In [168]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data,4,precision =2)
quartiles

[(-0.022, 0.66], (-0.73, -0.022], (-0.022, 0.66], (-3.44, -0.73], (0.66, 3.35], ..., (-0.022, 0.66], (0.66, 3.35], (-0.022, 0.66], (-0.73, -0.022], (0.66, 3.35]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.44, -0.73] < (-0.73, -0.022] < (-0.022, 0.66] < (0.66, 3.35]]

In [170]:
pd.value_counts(quartiles)

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.44, -0.73]     250
(-0.73, -0.022]    250
(-0.022, 0.66]     250
(0.66, 3.35]       250
Name: count, dtype: int64

In [172]:
pd.qcut(data, [0,0.1,0.5,0.9,1.]).value_counts()

(-3.4339999999999997, -1.339]    100
(-1.339, -0.0224]                400
(-0.0224, 1.239]                 400
(1.239, 3.353]                   100
Name: count, dtype: int64

#### 이상치 찾고 제외하기

In [183]:
data = pd.DataFrame(np.random.standard_normal((1000,4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.011560     0.021993    -0.030936    -0.015419
std       1.013551     1.009555     1.034154     1.007641
min      -3.934328    -3.060543    -3.470762    -3.352613
25%      -0.677388    -0.662365    -0.743830    -0.698736
50%       0.046476     0.040991    -0.032471    -0.003878
75%       0.688539     0.699936     0.672859     0.691668
max       3.390945     3.333205     3.004038     2.794955

In [185]:
col = data[2]
col[col.abs()>3]

213    3.004038
459   -3.470762
Name: 2, dtype: float64

In [189]:
data[(data.abs()>3).any(axis="columns")]

0         1         2         3
213  0.203689  0.412928  3.004038  1.547495
227 -3.934328 -1.479126  0.331709 -0.745687
275  0.322601  0.793969 -0.913680 -3.343754
325  1.734946  3.002512  0.498048  1.035324
436  1.344319  3.153395 -0.847592  0.348252
459  0.423842 -1.037143 -3.470762  0.539072
489 -1.083753  3.333205  1.358766  1.711154
532  0.356194  3.016076  1.111144  1.685970
678  0.698339 -0.085603 -0.682245 -3.113867
763  0.127164  0.559200 -0.054886 -3.352613
810  3.390945  0.839069  0.915035  0.374890
852 -2.167054  1.944680 -1.752111 -3.021992
888  1.433203 -1.737706 -0.674570 -3.059244
933  0.125648  0.884211  0.906692 -3.002790
990 -1.374792 -3.060543 -0.348269  0.634482

In [193]:
data[data.abs()>3] = np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.012103     0.021549    -0.030469    -0.014525
std       1.009101     1.007811     1.032681     1.004856
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.677388    -0.662365    -0.743830    -0.698736
50%       0.046476     0.040991    -0.032471    -0.003878
75%       0.688539     0.699936     0.672859     0.691668
max       3.000000     3.000000     3.000000     2.794955

In [195]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0 -1.0 -1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4  1.0 -1.0  1.0  1.0

#### 뒤섞기와 샘플링

In [198]:
df = pd.DataFrame(np.arange(5*7).reshape((5,7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [200]:
sampler = np.random.permutation(5)
sampler

array([3, 2, 0, 4, 1])

In [202]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [204]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [206]:
column_sampler = np.random.permutation(7)
column_sampler

array([2, 0, 1, 4, 6, 5, 3])

In [208]:
df.take(column_sampler, axis = "columns")

2   0   1   4   6   5   3
0   2   0   1   4   6   5   3
1   9   7   8  11  13  12  10
2  16  14  15  18  20  19  17
3  23  21  22  25  27  26  24
4  30  28  29  32  34  33  31

In [210]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [212]:
choices = pd.Series([5,7,-1,6,4])
choices.sample(n=10, replace= True)

1    7
2   -1
4    4
4    4
4    4
4    4
2   -1
1    7
0    5
2   -1
dtype: int64

#### 표시자, 더미 변수 계산하기

In [216]:
df = pd.DataFrame({"key": ["b","b","a","c","a","b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [218]:
pd.get_dummies(df["key"],dtype=float)

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [224]:
dummies = pd.get_dummies(df["key"],prefix="key",dtype=float)
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [234]:
mnames = ["movie_id", "title","genres"]
movies = pd.read_table("movies.dat", sep="::", header=None, names=mnames, engine="python", encoding="ISO-8859-1")


movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [236]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [238]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [240]:
np.random.seed(12345)
values = np.random.uniform(size =10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [242]:
bins = [0,0.2,0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

#### 확장 데이터 유형

In [245]:
s = pd.Series([1,2,3,None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [249]:
s.dtype

dtype('float64')

In [251]:
s = pd.Series([1,2,3,None], dtype =pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [253]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [255]:
s.dtype

Int64Dtype()

In [257]:
s[3]

<NA>

In [259]:
s[3] is pd.NA

True

In [261]:
s = pd.Series([1,2,3,None], dtype = "Int64")

In [263]:
s = pd.Series(['one','two',None, 'three'], dtype = pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [265]:
df = pd.DataFrame({"A": [1,2,None,4],
                   "B": ["one", "two","three", None],
                   "C": [False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [269]:
df["A"] = df["A"].astype('Int64')
df["B"] = df["B"].astype('string')
df["C"] = df["C"].astype('boolean')
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

#### 문자열 다루기


In [272]:
val = "a,b, guido"
val.split(",")

['a', 'b', ' guido']

In [274]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [276]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [278]:
"::".join(pieces)

'a::b::guido'

In [280]:
"guido" in val

True

In [282]:
val.index(",")

1

In [284]:
val.find(":")

-1

In [286]:
val.count(",")

2

In [288]:
val.replace(",", "::")

'a::b:: guido'

In [290]:
val.replace(",", "")

'ab guido'

#### 정규 표현식

In [309]:
import re

In [319]:
text = "foo    bar\t bax \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'bax', 'qux']

In [329]:
regex = re.compile(r"s\+")
regex.split(text)

['foo    bar\t bax \tqux']

In [327]:
regex.findall(text)

[]

In [331]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regex = re.compile(pattern, flags = re.IGNORECASE)

In [333]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [335]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [337]:
text[m.start():m.end()]

'dave@google.com'

In [339]:
print(regex.match(text))

None


In [341]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [349]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [351]:
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [353]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [355]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


#### 판다스의 문자열 함수

In [360]:
data = {"Dave": "dave@google.come", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data

Dave     dave@google.come
Steve     steve@gmail.com
Rob         rob@gmail.com
Wes                   NaN
dtype: object

In [362]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [364]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [366]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dave@google.come
Steve     steve@gmail.com
Rob         rob@gmail.com
Wes                  <NA>
dtype: string

In [368]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [370]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, come)]
Steve     [(steve, gmail, com)]
Rob         [(rob, gmail, com)]
Wes                         NaN
dtype: object

In [372]:
matches = data.str.findall(pattern, flags = re.IGNORECASE).str[0]
matches

Dave     (dave, google, come)
Steve     (steve, gmail, com)
Rob         (rob, gmail, com)
Wes                       NaN
dtype: object

In [374]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [376]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [378]:
data.str.extract(pattern, flags = re.IGNORECASE)

0       1     2
Dave    dave  google  come
Steve  steve   gmail   com
Rob      rob   gmail   com
Wes      NaN     NaN   NaN

#### Categorical Data

In [381]:
values = pd.Series(['apple', 'orange', 'apple','apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [383]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [385]:
pd.value_counts(values)

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [387]:
values = pd.Series([0,1,0,0]*2)
dim = pd.Series(["apple", "orange"])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [389]:
dim

0     apple
1    orange
dtype: object

In [391]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

#### 판다스의 Categorical 확장형

In [396]:
fruits = ['apple', 'orange','apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed = 12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3,15,size=N),
                   'weight': rng.uniform(0,4,size = N)},
                  columns = ['basket_id', 'fruit', 'count', 'weight'])

df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [398]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [400]:
c = fruit_cat.array

In [402]:
type(c)

pandas.core.arrays.categorical.Categorical

In [404]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [406]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [408]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [410]:
df['fruit'] = df["fruit"].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [412]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [414]:
categories = ['foo', 'bar', 'baz']
codes = [0,1,2,0,0,1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [416]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered = True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [420]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

#### Categorical Calculation

In [423]:
rng = np.random.default_rng(seed =12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [425]:
bins = pd.qcut(draws,4, labels = ['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [427]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [429]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count','min','max'])
           .reset_index())
results

C:\Users\JuhyunN\AppData\Local\Temp\ipykernel_6860\2290329183.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [431]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [433]:
N = 10_000_000
labels = pd.Series(['foo','bar','baz', 'qux'] * (N//4))
categories = labels.astype('category')
labels.memory_usage(deep=True)

520000132

In [435]:
categories.memory_usage(deep=True)

10000512

In [437]:
%time _ = labels.astype('category')

CPU times: total: 672 ms
Wall time: 749 ms


In [439]:
%timeit labels.value_counts()

841 ms ± 22.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [441]:
%timeit categories.value_counts()

84.4 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [443]:
s = pd.Series(['a','b','c','d'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [445]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [447]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [449]:
actual_categories = ['a','b','c', 'd','e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [451]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [453]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [455]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [457]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [459]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] *2,dtype = 'category')

In [461]:
pd.get_dummies(cat_s, dtype=float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0